version: "2"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080